### ISSUE TITLE
localstack + chalice-local with hotrealoder

### ISSUE THREAD

**Issue by jonathanabila** [localstack/chalice-local#5]
I'm trying to create a local environment using localstack + chalice-local + docker, The idea is to have a fully functional local environment inside the docker.

The current problem is how can I create a hot reloader using localstack and chalice-local? 

Every time that I change some code, I have to redeploy chalice again - this is kind of not productive, it would be amazing to have a way to implement this hot reload.

My current localstack setting is:
```yaml
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      SERVICES: sqs,s3,cloudwatch,lambda,logs,iam,apigateway
      EDGE_PORT: 4566
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack
      # The version will be added automatically, in this case python3.8.
      LAMBDA_CONTAINER_REGISTRY: lambci/local-lambda
      LAMBDA_REMOVE_CONTAINERS: "false"
      LAMBDA_REMOTE_DOCKER: "false"
      HOST_TMP_FOLDER: "/tmp/localstack"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I'm also using a custom lambda container to execute my code, so I don't need to use lambda layers, here is my docker file:
```dockerfile
FROM lambci/lambda:python3.8 as builder

WORKDIR /app

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

COPY poetry.lock pyproject.toml ./

# Changes the user to be able to install the dependencies
USER root

RUN python -m pip install --upgrade pip

# Install requirements
RUN pip install "poetry==1.1.6"
RUN poetry config virtualenvs.create false
# Local environment doesn't need the dev libraries to work
RUN poetry install --no-interaction --no-ansi --no-dev

# User used by the base image (lambci)
USER sbx_user1051

COPY . /app/
WORKDIR /app/src
```

My project is very simple, I'm trying to validate the behavior before putting it into practice.

```python
import requests
from chalice import Chalice

app = Chalice("ftc-api")


@app.route("/", methods=["POST", "GET"])
def index():

    # Chalice receives a request from Hasura
    # Chalice makes a request to Hasura
    response = requests.get("http://hasura:8080/healthz")
    if response.ok:
        return {"data": True}
    return {"data": False}


@app.on_sqs_message(queue="my-queue", batch_size=1)
def handle_my_queue_message(event):
    print("# " * 20)
    return {"data": True}
```

Currently, I tried different settings on localstack:

#### mapping src to /app/src
Using a volume to map the source of my project to where I copied all my files inside docker "./src/:/app/src" - It didn't work because the code executed by localstack is in another folder, tmp/localstack, and I also received this error:
`Running lambda cmd: docker run -i  -v "/tmp/localstack/zipfile.1d33006a":/var/task`

It also returns this error:
`localstack_1  | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'app': No module named 'app'"}. Output:` 
I wasn't able to understand yet why and how to fix it.

#### mapping src to /tmp/localstack
But I got the same error:
`{"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'app': No module named 'app'"}`

Someone tried something along these lines and has any idea how to make this hot reloader structure work and if it is possible to do it?

**Comment by craigmulligan** [comment]
hey @jonathanabila did you get anywhere with this? I've trying to set up something similar (fast local chalice development connected to the sns service from localstack). I've been trying to use local stacks `LAMBDA_FORWARD_URL` to proxy requests to `chalice local` server but haven't gotten very far yet.

**Comment by jonathanabila** [comment]
@hobochild I managed to create the hotrealoder, but it's not like I thought at the beginning, the end result is this:


### docker-compose.yml
```yaml
version: "3.9"

services:
  watcher:
    build:
      context: .
      dockerfile: watcher.Dockerfile
    image: ftc/watcher:local
    environment:
      LOCALSTACK_PATH: "/tmp/localstack/"
    command: python watcher.py /tmp/src
    volumes:
      - ./src/:/tmp/src
      - /tmp/localstack/:/tmp/localstack/

  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    image: ftc/deploy:local
    env_file:
      - .env.local
    command: bin/localstack
    volumes:
      - .:/tmp/
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      SERVICES: sqs,s3,cloudwatch,lambda,logs,iam,apigateway
      EDGE_PORT: 4566
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack
      # The version will be added automatically, in this case python3.8.
      LAMBDA_CONTAINER_REGISTRY: lambci/local-lambda
      LAMBDA_REMOVE_CONTAINERS: "false"
      LAMBDA_REMOTE_DOCKER: "false"
    volumes:
      - /tmp/localstack/:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - watcher

  ftc_lambdas:
    build:
      context: .
      dockerfile: lambdas.Dockerfile
    image: lambci/local-lambda:python3.8
    environment:
      HASURA_ENDPOINT: http://hasura:8080
    volumes:
      - .:/app/
    env_file:
      - .env.local
    depends_on:
      - localstack

  ftc_api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: ftc/api:local
    command: chalice local --port 8081 --host 0.0.0.0
    environment:
      HASURA_ENDPOINT: http://hasura:8080
    ports:
      - 8081:8081
    volumes:
      - .:/app/
    env_file:
      - .env.local

  ...
```

## Deploy service
Executes every time that localstack starts.

### `bin/localstack`
```bash
#!/bin/bash
set -euf
IFS=$'\n\t'

echo "Waiting localstack to be ready"
waitforit --timeout=0 localstack:4566

echo "Setting up environment"
aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name catalog-api-local-my-queue | tee /dev/null
echo "Finished"

echo "Deploying chalice"
export LOCALSTACK_HOST="localstack"
cd /tmp/src
# TODO: When we try to perform a deployment with an existing file it gives error 404 in the gateway api.
rm -rf .chalice/deployed/local.json

chalice-local deploy --stage local
echo "Chalice deployed"
```

### deploy.Dockerfile
```dockerfile
FROM python:3.8.5-slim as builder

RUN apt-get update \
    && apt-get install curl unzip -y \
    && apt-get clean

# add a script to wait until the localstack is ready to receive the deploys
RUN curl -o /usr/local/bin/waitforit -sSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x /usr/local/bin/waitforit

# Install aws cli v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.2.3.zip" -o ./"awscliv2.zip"

RUN unzip awscliv2.zip
RUN ./aws/install -i /usr/local/aws -b /usr/local/bin

RUN rm -rf ./aws

WORKDIR /app

COPY poetry.lock pyproject.toml ./

RUN python -m pip install --upgrade pip

# Install requirements
RUN pip install "poetry==1.1.6"
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

# copies the automation scripts
COPY bin/ /app/bin/

ENTRYPOINT []
```

## API Server
I didn't manage to execute the lambdas using SQS with lambci, so i created two different images:

### API
```dockerfile
FROM lambci/lambda:build-python3.8 as builder

WORKDIR /app

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

COPY poetry.lock pyproject.toml ./

RUN python -m pip install --upgrade pip

# Install requirements
RUN pip install "poetry==1.1.6"
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

COPY . /app/
WORKDIR /app/src
```

### Lambdas (To be trigged)
```dockerfile
FROM lambci/lambda:python3.8 as builder

WORKDIR /app

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

COPY poetry.lock pyproject.toml ./

# Changes the user to be able to install the dependencies
USER root

RUN python -m pip install --upgrade pip

# Install requirements
RUN pip install "poetry==1.1.6"
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

# User used by the base image (lambci)
USER sbx_user1051

COPY . /app/
WORKDIR /app/src
```

## Watcher
And watcher, that is responsible for deploying everything for every change.
```dockerfile
FROM python:3.8.5-slim

RUN apt-get update \
    && pip install --upgrade pip \
    # Improves watcher's performance https://github.com/gorakhargosh/watchdog
    && apt-get install libyaml-dev -y \
    && pip install watchdog

COPY bin.py/watcher.py /app/
WORKDIR /app/
```

```python
import logging
import os
import sys
import time
from distutils.dir_util import copy_tree
from pathlib import Path

from watchdog.events import PatternMatchingEventHandler
from watchdog.observers import Observer

SHARED_LOCALSTACK_VOLUME_PATH = os.environ.get("LOCALSTACK_PATH")

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
)

logger = logging.getLogger(__name__)


class DockerEventHandler(PatternMatchingEventHandler):
    patterns = ["*.py"]

    def __init__(
        self,
        source_path,
        patterns=None,
        ignore_patterns=None,
        ignore_directories=False,
        case_sensitive=False,
    ):
        self.source_path = source_path

        patterns = patterns or self.patterns
        super().__init__(patterns, ignore_patterns, ignore_directories, case_sensitive)

    def on_any_event(self, event):
        p = Path(SHARED_LOCALSTACK_VOLUME_PATH)
        folders = [f for f in p.iterdir() if f.is_dir()]

        for folder in folders:
            dest = SHARED_LOCALSTACK_VOLUME_PATH + folder.name
            # logger.info(f"Copying file to: {dest}")
            copy_tree(self.source_path, dest)


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "."
    event_handler = DockerEventHandler(path)
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    finally:
        observer.stop()
        observer.join()

```

If you have any ideas on how to improve, or something that didn't work, let me know :rocket:
